// src/shmup/level/campaign.js
// Purpose: the ten-level campaign — themes, a level factory, boss configs, and
// progression. Import-clean data (stage-lint runs it headless).
// Dependencies: level01 (bespoke), palette helpers, engine/settings (progress)
//
// NARRATIVE_PLAN §5 (the bible's ten levels). Level 01 is hand-authored in
// level01.js; levels 02-10 are generated by makeLevel() from a per-level THEME
// (palette + enemy mix + boss + cutscene ids) over the LEVELS_PLAN §4 pacing
// skeleton, so every one is stage-lint-clean by construction. Each still reads
// distinctly: its own colors, its own enemy mix, its own boss and banter.

import { LEVEL01 } from './level01.js';
import { setProgress, getProgress } from '../../engine/settings.js';

// ── per-level themes. Colors are {base,mid,dark,pale,flesh} for the tunnel +
//    parallax; enemies is the archetype mix this level draws waves from.
export const THEMES = [
    null,   // index 0 unused; levels are 1-based
    null,   // level 1 is LEVEL01 (bespoke)
    { name: 'THE INDUCTION PARROT', pal: { base: 0x8892a0, mid: 0x6a7482, dark: 0x3e4652, pale: 0xc0cad8, flesh: 0x545e6c }, enemies: ['darter', 'drone', 'gunpod'], boss: 'boss02' },
    { name: 'THE JESTER UNBOUND', pal: { base: 0x9a4a7a, mid: 0x6e3358, dark: 0x3a1a30, pale: 0xe070c0, flesh: 0x7a2a5a }, enemies: ['drone', 'mine', 'darter'], boss: 'boss03' },
    { name: 'THE SMOOTH OPERATOR', pal: { base: 0xb8b0a0, mid: 0x8a8478, dark: 0x54504a, pale: 0xd8d0c0, flesh: 0x6a665e }, enemies: ['gunpod', 'lancer', 'drone'], boss: 'boss04' },
    { name: 'THE MIRROR BREAK', pal: { base: 0x88a0b8, mid: 0x5a7088, dark: 0x30404e, pale: 0xd0e4f4, flesh: 0x486074 }, enemies: ['darter', 'mine', 'lancer'], boss: 'boss05' },
    { name: 'THE REDEMPTION ARC', pal: { base: 0xf0c0d8, mid: 0xd89ab8, dark: 0x9a6a86, pale: 0xffe0f0, flesh: 0xc888a8 }, enemies: ['drone', 'mine'], boss: 'boss06' },
    { name: 'THE FORGE WRAITH', pal: { base: 0xc06838, mid: 0x8a3e1e, dark: 0x401810, pale: 0xffa860, flesh: 0x6a2810 }, enemies: ['gunpod', 'lancer', 'crawler'], boss: 'boss07' },
    { name: 'THE DRIFT WRAITH', pal: { base: 0xc8c8cc, mid: 0x9a9aa0, dark: 0x66666c, pale: 0xeeeef2, flesh: 0x80808a }, enemies: ['drone', 'darter', 'lancer'], boss: 'boss08' },
    { name: "THE WITNESS'S SHADOW", pal: { base: 0x6a5a8a, mid: 0x453a5e, dark: 0x241d34, pale: 0x9a86c8, flesh: 0x352a4c }, enemies: ['darter', 'mine', 'gunpod'], boss: 'boss09' },
    { name: 'THE CORRUPTED SEAL', pal: { base: 0x8a7ac8, mid: 0x5a4e8e, dark: 0x2c2450, pale: 0xc0b0ff, flesh: 0x443a70 }, enemies: ['lancer', 'mine', 'darter', 'gunpod'], boss: 'boss10' }
];

/**
 * Generate a stage-lint-clean level for a theme. The pacing skeleton is fixed
 * (teach -> checkpoint+recovery -> rising -> lock gauntlet -> checkpoint+recovery
 * -> pre-boss -> boss), the CONTENT is the theme's enemy mix.
 */
export function makeLevel(id) {
    const theme = THEMES[id];
    if (!theme) return null;
    const [e0, e1, e2] = [theme.enemies[0], theme.enemies[1] || theme.enemies[0], theme.enemies[2] || theme.enemies[0]];
    const LENGTH = 340;
    const CHUNK = 5;      // fleshWall(20) * 0.25 world width

    const terrain = [];
    for (let x = 0; x * CHUNK < LENGTH + CHUNK; x++) {
        terrain.push({ chunk: 'fleshWall', atX: x * CHUNK, y: 0, args: [20, 5, 1], palette: theme.pal });
        terrain.push({ chunk: 'fleshWall', atX: x * CHUNK, y: 16, args: [20, 5, -1], palette: theme.pal });
    }

    const triggers = [
        { atX: 18, type: 'dialogue', id: 'L' + pad(id) + '_open' },
        { atX: 26, type: 'wave', formation: 'chain', enemy: e0, count: 5, y: 8, spacing: 1.6, params: { amp: 1.6, freq: 0.45 } },
        { atX: 54, type: 'wave', formation: 'chain', enemy: e0, count: 5, y: 11, spacing: 1.5, params: { amp: 1.4, freq: 0.5 } },
        { atX: 72, type: 'wave', formation: 'turretNest', enemy: e2 === 'gunpod' ? 'gunpod' : e1, count: 1, y: 8 },
        { atX: 92, type: 'wave', formation: 'escort', enemy: e0, count: 2, y: 7 },
        { atX: 110, type: 'checkpoint' },
        { atX: 116, type: 'pickup', kind: 'shard', y: 8, recoveryOnly: true },
        { atX: 132, type: 'wave', formation: 'chain', enemy: e1, count: 3, y: 10, spacing: 2.0 },
        { atX: 152, type: 'wave', formation: 'column', enemy: e0, count: 4, y: 8, spacing: 2.4 },
        { atX: 172, type: 'wave', formation: 'pincer', enemy: e1, count: 6, y: 8, spacing: 1.6 },
        { atX: 190, type: 'pickup', kind: 'bit', y: 6 },
        { atX: 200, type: 'wave', formation: 'chain', enemy: e2, count: 2, y: 8, spacing: 2.0 },
        { atX: 224, type: 'lock', until: 'cleared' },
        { atX: 225, type: 'wave', formation: 'chain', enemy: e0, count: 5, y: 6, spacing: 1.4 },
        { atX: 226, type: 'wave', formation: 'chain', enemy: e1, count: 4, y: 10, spacing: 1.5 },
        { atX: 240, type: 'checkpoint' },
        { atX: 246, type: 'pickup', kind: 'shard', y: 8, recoveryOnly: true },
        { atX: 258, type: 'wave', formation: 'escort', enemy: e0, count: 2, y: 9 },
        { atX: 276, type: 'pickup', kind: 'shard', y: 5 },
        { atX: 300, type: 'speed', scrollSpeed: 0 },
        { atX: 300, type: 'dialogue', id: 'L' + pad(id) + '_boss' },
        { atX: 306, type: 'boss', id: theme.boss },
        { atX: 320, type: 'end' }
    ];

    return {
        id,
        name: theme.name,
        scrollSpeed: 2.6,
        length: LENGTH,
        music: 'beige',           // Phase 8 ships one track; per-level tracks later
        palette: { sky: 0x0a0514, fogDensity: 0.004 },
        checkpoints: [110, 240],
        parallax: [],
        terrain,
        triggers,
        _theme: theme
    };
}

function pad(n) { return n < 10 ? '0' + n : '' + n; }

// The full campaign, 1-based via index. Level 01 is bespoke; the rest generated.
export const LEVELS = [null, LEVEL01,
    makeLevel(2), makeLevel(3), makeLevel(4), makeLevel(5),
    makeLevel(6), makeLevel(7), makeLevel(8), makeLevel(9), makeLevel(10)];

export const LAST_LEVEL = 10;

/** The level the player should start (from saved progress), clamped. */
export function levelToPlay() {
    const p = getProgress();
    const reached = (p.rtype && p.rtype.stageReached) || 1;
    return Math.max(1, Math.min(LAST_LEVEL, reached));
}

/** Record that level `id` was cleared: unlock the next level + its codex. */
export function recordClear(id) {
    const p = getProgress();
    const rtype = Object.assign({ stageReached: 1, checkpoint: 0, loops: 0 }, p.rtype);
    rtype.stageReached = Math.max(rtype.stageReached, Math.min(LAST_LEVEL + 1, id + 1));
    setProgress({ rtype });
}

export function getLevel(id) {
    return LEVELS[id] || null;
}
